---
- name: Kube-OVN | Label ovn-db node
  command: >-
    {{ kubectl }} label node -lnode-role.kubernetes.io/control-plane kube-ovn/role=master --overwrite
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: Kube-OVN | Create Kube-OVN manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kube_config_dir }}/{{ item.file }}"
    mode: 0644
  with_items:
    - {name: kube-ovn-crd, file: cni-kube-ovn-crd.yml}
    - {name: ovn, file: cni-ovn.yml}
    - {name: kube-ovn, file: cni-kube-ovn.yml}
  register: kube_ovn_node_manifests
